// Generated by CoffeeScript 1.3.3

describe("Money", function() {
  it("should true", function() {
    return true;
  });
  return describe("#format", function() {
    it("returns the monetary value as a string", function() {
      var money;
      money = new Money(123456, 'EUR');
      return expect(money.formatted()).toEqual("1234,56 €");
    });
    it("does not display a decimal when factor is 1", function() {
      var money;
      money = new Money(1000, 'CLP');
      return expect(money.formatted()).toEqual("$1000");
    });
    return describe(":no_cents option", function() {
      it("filters when value has no decimals", function() {
        var money;
        money = new Money(1000, 'EUR', {
          no_cents: true
        });
        return expect(money.formatted()).toEqual("10 €");
      });
      return it("filters when value has decimals", function() {
        var money;
        money = new Money(1040, 'EUR', {
          no_cents: true
        });
        return expect(money.formatted()).toEqual("10 €");
      });
    });
  });
});
